CREATE TABLE `real_estate`.`real_estate_nz` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `propertyId` varchar(50) DEFAULT NULL,
  `propertyName` varchar(200) DEFAULT NULL,
  `area` varchar(50) DEFAULT NULL,
  `bed` varchar(50) DEFAULT NULL,
  `parking` varchar(50) DEFAULT NULL,
  `category` varchar(100) DEFAULT NULL,
  `publishedDate` varchar(50) DEFAULT NULL,
  `createdDate` date DEFAULT NULL,
  `created` datetime DEFAULT CURRENT_TIMESTAMP,
  `modified` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `propertyType` varchar(50) DEFAULT NULL,
  `areaUnit` varchar(45) DEFAULT NULL,
  `parkingOtherCount` varchar(45) DEFAULT NULL,
  `parkingGarageCount` varchar(45) DEFAULT NULL,
  `storyCount` varchar(45) DEFAULT NULL,
  `maxTenants` varchar(45) DEFAULT NULL,
  `floorArea` varchar(45) DEFAULT NULL,
  `bathCount` varchar(45) DEFAULT NULL,
  `bathEnsuiteCount` varchar(45) DEFAULT NULL,
  `bathWcCount` varchar(45) DEFAULT NULL,
  `hasSwimmingPool` varchar(45) DEFAULT NULL,
  `streetNumber` varchar(45) DEFAULT NULL,
  `street` varchar(100) DEFAULT NULL,
  `postCode` varchar(45) DEFAULT NULL,
  `address` varchar(200) DEFAULT NULL,
  `country` varchar(45) DEFAULT NULL,
  `region` varchar(100) DEFAULT NULL,
  `district` varchar(45) DEFAULT NULL,
  `latitude` varchar(45) DEFAULT NULL,
  `longitude` varchar(45) DEFAULT NULL,
  `subUrb` varchar(100) DEFAULT NULL,
  `nearBySuburb` varchar(700) DEFAULT NULL,
  `nearBySuburbSlugs` varchar(700) DEFAULT NULL,
  `offices` varchar(700) DEFAULT NULL,
  `agents` varchar(700) DEFAULT NULL,
  `schools` varchar(700) DEFAULT NULL,
  `additionalWebsites` varchar(700) DEFAULT NULL,
  `listingId` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `propertyId` (`propertyId`)
);

CREATE TABLE `real_estate`.`real_estate_nz_pricing` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `propertyKey` int(11) DEFAULT NULL,
  `price` varchar(150) DEFAULT NULL,
  `createdDate` date DEFAULT NULL,
  `created` datetime DEFAULT CURRENT_TIMESTAMP,
  `modified` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `listingStatus` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `real_estate_nz_pricing_uc` (`createdDate`,`propertyKey`),
  KEY `propertyKey` (`propertyKey`),
  CONSTRAINT `real_estate_nz_pricng_ibfk_1` FOREIGN KEY (`propertyKey`) REFERENCES `real_estate_nz` (`id`)
);
